# from Top_functions import *
import streamlit as st
import os, time, base64
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.sql import text
from datetime import datetime
import matplotlib.pyplot as plt
from dotenv import load_dotenv
load_dotenv()

st.set_page_config(
    layout="wide",
    page_icon="🤖",
    )

# Database connection parameters
db_host = os.getenv('DB_HOST')
db_user = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')
db_port = os.getenv('DB_PORT')
db_name = os.getenv('DB_NAME')

engine = create_engine(f'mysql+mysqlconnector://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}',  pool_size=10, max_overflow=20)

INITIAL_FUND = int(os.getenv('INITIAL_FUND', 100_000))


def format_number(num):
    if not num:
        return 0
    if type(num) is dict:
        print(num)
        return 0
    if type(num) is not str and not float and not int:
        return num
    if type(num) is str:
        try:
            num = float(num)
        except Exception as e:
            return num
    positive = 1 if num >= 0 else -1
    num = abs(num)
    if num >= 1000:
        num = int(num)
        num = num * positive
        num = format(num, ',')
        return num
    if num >= 100:
        num = int(num)
        return num * positive
    if num >= 1:
        num = round(num, 2)
        return num * positive
    if num < 0.0001:
        return num * positive
    if num < 1:
        after_0_num = str(num).split('.')[-1]
        list_number = list(after_0_num)
        for i in range(len(list_number)):
            if int(list_number[i]) != 0:
                zero_num = i
                break
        num = round(num, zero_num + 3)
        return num * positive
    

def display_header():
    st.markdown("<h1 style='text-align: center;'>Trading Bot Performance Dashboard</h1>", unsafe_allow_html=True)
    st.markdown("<center>This dashboard provides insights into the Trading Bot's performance.</center>", unsafe_allow_html=True)

def plot_annualized_return():
    query = "SELECT Date, NetProfit FROM net_profit_daily_record"
    with engine.connect() as connection: df = pd.DataFrame(connection.execute(text(query)).fetchall(), columns=['Date', 'NetProfit'])

    # Calculate Bot Running Time
    with engine.connect() as connection: df_earliest = pd.DataFrame(connection.execute(text('SELECT MIN(time_create) FROM position_table')).fetchall(), columns=['time_create'])
    earliest_transactTime = df_earliest['time_create'].iloc[0]
    duration = (int(time.time() * 1000) - earliest_transactTime) / 1000 / 60 / 60
    duration_day = f'{int(duration / 24)} D {int(duration % 24)} H' if duration > 24 else f'{int(duration)} Hours'

    # Calculate Annualized APY
    with engine.connect() as connection: df_profit = pd.DataFrame(connection.execute(text('SELECT SUM(profit) FROM position_table WHERE is_closed = 1 AND account = "spot"')).fetchall(), columns=['profit'])
    profit_sum = df_profit['profit'].iloc[0]
    profit_sum = float(profit_sum)
    roi = profit_sum / INITIAL_FUND
    annualized_return = profit_sum / (duration / 24 / 365) / INITIAL_FUND
    annualized_return_percent = f"{annualized_return * 100:.2f}%"

    # Calculate Return as a Percentage
    df['ReturnPercent'] = (df['NetProfit'] / INITIAL_FUND) * 100

    metric_col1, metric_col2, metric_col3 = st.columns(3)
    metric_col1.metric("DUATION", duration_day, datetime.utcfromtimestamp(earliest_transactTime/1000).strftime('%Y-%m-%d'))
    metric_col2.metric("ROI", f"{format_number(roi*100)}%", format_number(profit_sum))
    metric_col3.metric("APY", annualized_return_percent, format_number(annualized_return))
    
    fig, ax1 = plt.subplots(figsize=(12, 8))

    ax1.plot(df['Date'], df['NetProfit'], color='green')
    ax1.set_ylabel('Net Profit', color='black')

    # Create a secondary y-axis for the percentage return
    ax2 = ax1.twinx()
    ax2.plot(df['Date'], df['ReturnPercent'], color='green')
    ax2.set_ylabel('Return (%)', color='black')

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("<h1 style='text-align: center;'>Annualized Return Chart</h1>", unsafe_allow_html=True)
        plt.title('Daily Return')
        st.pyplot(fig)

    with col2:
        st.markdown("<h1 style='text-align: center;'>Performance by Coin</h1>", unsafe_allow_html=True)
        plt.title('Performance by coin')
        plot_performance_by_coin()

    return

def plot_performance_by_coin():
    # Query to calculate the total profit generated by each symbol
    sell_query = "SELECT symbol, SUM(profit) as total_profit FROM position_table GROUP BY symbol"
    sell_count_query = "SELECT symbol, COUNT(*) as trade_count FROM position_table GROUP BY symbol"
    
    with engine.connect() as connection: result = connection.execute(text(sell_query)).fetchall()
    df_sell = pd.DataFrame(result, columns=['symbol', 'total_profit'])
    
    with engine.connect() as connection: count_result = connection.execute(text(sell_count_query)).fetchall()
    df_count = pd.DataFrame(count_result, columns=['symbol', 'trade_count'])

    # Merge the two dataframes on symbol
    df_merged = pd.merge(df_sell, df_count, on='symbol')
    
    # Add a new column 'coin' by slicing the 'symbol' column
    df_merged['coin'] = df_merged['symbol'].str[:-4]

    df_merged['total_profit'] = pd.to_numeric(df_merged['total_profit'], errors='coerce')

    # Filter to top 10 positive and top 5 negative profit coins
    top_positive = df_merged[df_merged['total_profit'] > 0].nlargest(5, 'total_profit')
    top_negative = df_merged[df_merged['total_profit'] < 0].nsmallest(5, 'total_profit')
    df_filtered = pd.concat([top_positive, top_negative]).sort_values(by='total_profit', ascending=False)

    colors = ['red' if x < 0 else 'green' for x in df_filtered['total_profit']]
    
    # Plotting the total profit
    fig, ax1 = plt.subplots(figsize=(12, 8))
    ax1.bar(df_filtered['coin'], df_filtered['total_profit'], color=colors)
    ax1.set_ylabel('Total Profit', color='black')
    ax1.tick_params(axis='y', labelcolor='black')

    # Create a secondary y-axis for trade count
    ax2 = ax1.twinx()
    ax2.plot(df_filtered['coin'], df_filtered['trade_count'], color='grey', marker='o', linestyle='-')
    ax2.set_ylabel('Trade Count', color='black')
    ax2.tick_params(axis='y', labelcolor='black')

    # Add labels and title
    plt.xticks(rotation=45)
    # ax1.set_xlabel('Coins')
    plt.title('Top Performing and Worst Performing Coins')

    st.pyplot(fig)
    return 


def display_binance_trading_history():
    try:
        with engine.connect() as connection: df_merged = pd.DataFrame(connection.execute(text('SELECT * FROM position_table WHERE is_closed = 1 AND account = "spot" ORDER BY time_create DESC')).fetchall())
    except: df_merged = pd.DataFrame()
    if df_merged.empty: return
    df_merged['profit'] = pd.to_numeric(df_merged['profit'], errors='coerce').fillna(0)
    df_merged['duration_min'] = df_merged['duration'].apply(lambda x: int(x/1000/60))
    df_merged['time_create'] = df_merged['time_create'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
    df_merged['time_close'] = df_merged['time_close'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
    df_merged = df_merged[['coin', 'profit', 'account', 'type_create', 'type_close', 'duration_min', 'time_create', 'time_close', 'price_create', 'price_close', 'orderId_create', 'orderId_close']]
    df_merged.sort_values(by=['profit'], ascending=False, inplace=True)
    total_profit = df_merged['profit'].sum()
    csv = df_merged.to_csv(index=False)
    b64 = base64.b64encode(csv.encode()).decode()
    href = f'<a href="data:file/csv;base64,{b64}" download="binance_position_table.csv">Download CSV File</a>'
    st.markdown(href, unsafe_allow_html=True)
    with st.expander("Spot Account BUY & SELL History", expanded=False): 
        st.write(f"Total Profit: {format_number(total_profit)}")
        st.table(df_merged)
    # group by coin and make profit sum, show only the coin, profit columns
    df_merged = df_merged.groupby(['coin']).sum(numeric_only=True).astype(float)
    df_merged = df_merged[['profit']]
    df_merged.sort_values(by=['profit'], ascending=False, inplace=True)
    df_merged.reset_index(inplace=True)
    df_merged['profit'] = df_merged['profit'].apply(lambda x: format_number(x))
    with st.expander("Spot Account Performance Grouped by Coin", expanded=False): st.table(df_merged)
    return


def display_open_position():
    try:
        with engine.connect() as connection: df_buy = pd.DataFrame(connection.execute(text('SELECT coin, amount,account, orderId_create, time_create, price_create, orderId_close FROM position_table WHERE is_closed = 0 ORDER BY time_create DESC')).fetchall())
    except: df_buy = pd.DataFrame()
    if df_buy.empty: return
    df_buy['duration'] = int(time.time() * 1000) - df_buy['time_create']
    df_buy['duration_hour'] = df_buy['duration'].apply(lambda x: int(x/1000/60/60))
    df_buy['time_create'] = df_buy['time_create'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
    df_buy.drop(['duration'], axis=1, inplace=True)
    df_spot = df_buy[df_buy['account'] == 'spot']
    df_funding = df_buy[df_buy['account'] == 'funding']
    if not df_spot.empty: 
        with st.expander("Spot Account Open Positions", expanded=False): st.table(df_spot)
    if not df_funding.empty: 
        with st.expander("Funding Account Open Positions", expanded=False): st.table(df_funding)
    return 

def binance_pay_record():
    with engine.connect() as connection: 
        try: df = pd.DataFrame(connection.execute(text(f"SELECT * FROM binance_pay_records")).fetchall())
        except: df = pd.DataFrame()
    if df.empty: return 
    # select amount sum of total records
    total_amount = df['amount'].sum()
    # select amount sum of this year
    this_year_amount = df[df['created_at'].str.startswith(datetime.now().strftime('%Y'))]['amount'].sum()
    # select amount sum of this month
    this_month_amount = df[df['created_at'].str.startswith(datetime.now().strftime('%Y-%m'))]['amount'].sum()
    msg = f"Total payout: {format_number(total_amount)} | This year: {format_number(this_year_amount)} | This month: {format_number(this_month_amount)}"
    return msg


def display_funding_account_performance():
    try: 
        with engine.connect() as connection: df = pd.DataFrame(connection.execute(text(f'SELECT coin, profit, price_create, price_close, orderId_create, orderId_close, time_create, time_close, duration FROM position_table WHERE account = "funding" AND is_closed = 1')).fetchall())
    except: df = pd.DataFrame()
    if not df.empty:
        df['time_create'] = df['time_create'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
        df['time_close'] = df['time_close'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
        df['duration_hour'] = df['duration'].apply(lambda x: int(x/1000/60/60))
        df['profit'] = pd.to_numeric(df['profit'], errors='coerce').fillna(0)
        total_profit = df['profit'].sum()
        df.sort_values(by=['time_close'], ascending=False, inplace=True)
        df_latest = df.head(10).copy()
        df_latest['profit'] = df_latest['profit'].apply(lambda x: format_number(x))
        df_group = df.groupby(['coin']).sum(numeric_only=True).astype(float)
        df_group = df_group[['profit']]
        df_group.sort_values(by=['profit'], ascending=False, inplace=True)
        df_group.reset_index(inplace=True)
        df_group['profit'] = df_group['profit'].apply(lambda x: format_number(x))
        st.write(f"Funding Account Total Profit: {format_number(total_profit)} | Binance Pay: {binance_pay_record()} | Table shows last 10 records")
        with st.expander("Funding Account Performance", expanded=False): st.table(df_latest)
        with st.expander("Funding Account Performance Grouped by coin", expanded=False): st.table(df_group.head(10))


def display_daily_profit_take():
    try:
        with engine.connect() as connection: df_profit = pd.DataFrame(connection.execute(text(f'SELECT * FROM position_table WHERE is_closed = 1')).fetchall())
    except: df_profit = pd.DataFrame()
    if df_profit.empty: return
    df_profit['profit'] = pd.to_numeric(df_profit['profit'], errors='coerce').fillna(0)
    col1, col2, col3 = st.columns(3)
    with col1:
        df_daily_profit = df_profit.groupby(['year_close', 'month_close', 'day_close'])['profit'].sum(numeric_only=True).reset_index().astype(int)
        df_daily_profit = df_daily_profit[df_daily_profit['year_close'] == datetime.now().year]
        df_daily_profit['date'] = df_daily_profit['year_close'].astype(str) + '-' + df_daily_profit['month_close'].astype(str) + '-' + df_daily_profit['day_close'].astype(str)
        with st.expander("Daily Profit", expanded=False): st.table(df_daily_profit)
    with col2:
        df_monthly_profit = df_profit.groupby(['year_close', 'month_close'])['profit'].sum(numeric_only=True).reset_index().astype(int)
        df_monthly_profit['date'] = df_monthly_profit['year_close'].astype(str) + '-' + df_monthly_profit['month_close'].astype(str)
        with st.expander("Monthly Profit", expanded=False): st.table(df_monthly_profit)
    with col3:
        df_yearly_profit = df_profit.groupby(['year_close'])['profit'].sum(numeric_only=True).reset_index().astype(int)
        with st.expander("Yearly Profit", expanded=False): st.table(df_yearly_profit)

        
def display_ignore_list():
    try:
        with engine.connect() as connection: df = pd.DataFrame(connection.execute(text('SELECT coin FROM token_supply_info WHERE is_ignore = 1')).fetchall())
        if not df.empty: 
            with st.expander("Ignore List", expanded=False): st.table(df)
    except: pass

def display_white_list():
    try:
        with engine.connect() as connection: df = pd.DataFrame(connection.execute(text('SELECT coin FROM token_supply_info WHERE is_white = 1')).fetchall())
        if not df.empty: 
            with st.expander("White List", expanded=False): st.table(df)
    except: pass

def display_both_list():
    col1, col2 = st.columns(2)
    with col1: display_ignore_list()
    with col2: display_white_list()


def main():
    display_header()
    
    plot_annualized_return()

    display_open_position()

    display_binance_trading_history()

    display_funding_account_performance()

    display_daily_profit_take()

    display_both_list()
    

if __name__ == "__main__":
    main()
