# from Top_functions import *
import streamlit as st
import os, time
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.sql import text
from datetime import datetime
import matplotlib.pyplot as plt
from dotenv import load_dotenv
load_dotenv()

st.set_page_config(layout="wide")

# Database connection parameters
db_host = os.getenv('DB_HOST')
db_user = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')
db_port = os.getenv('DB_PORT')
db_name = os.getenv('DB_NAME')

engine = create_engine(f'mysql+mysqlconnector://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

INITIAL_FUND = int(os.getenv('INITIAL_FUND', 100_000))


def format_number(num):
    if not num:
        return 0
    if type(num) is dict:
        print(num)
        return 0
    if type(num) is not str and not float and not int:
        return num
    if type(num) is str:
        try:
            num = float(num)
        except Exception as e:
            return num
    positive = 1 if num >= 0 else -1
    num = abs(num)
    if num >= 1000:
        num = int(num)
        num = num * positive
        num = format(num, ',')
        return num
    if num >= 100:
        num = int(num)
        return num * positive
    if num >= 1:
        num = round(num, 2)
        return num * positive
    if num < 0.0001:
        return num * positive
    if num < 1:
        after_0_num = str(num).split('.')[-1]
        list_number = list(after_0_num)
        for i in range(len(list_number)):
            if int(list_number[i]) != 0:
                zero_num = i
                break
        num = round(num, zero_num + 3)
        return num * positive
    

def display_header():
    st.title("Trading Bot Performance Dashboard")
    st.text("This dashboard provides insights into the trading bot's performance.")

def plot_annualized_return(engine):
    query = "SELECT Date, NetProfit FROM net_profit_daily_record"
    df = pd.DataFrame(engine.connect().execute(text(query)).fetchall(), columns=['Date', 'NetProfit'])

    # Calculate Bot Running Time
    df_earliest = pd.DataFrame(engine.connect().execute(text('SELECT MIN(transactTime) FROM binance_position_buy')).fetchall(), columns=['transactTime'])
    earliest_transactTime = df_earliest['transactTime'].iloc[0]
    duration = (int(time.time() * 1000) - earliest_transactTime) / 1000 / 60 / 60
    duration_day = f'{int(duration / 24)} Days {int(duration % 24)} Hours' if duration > 24 else f'{int(duration)} Hours'

    # Calculate Annualized APY
    df_profit = pd.DataFrame(engine.connect().execute(text('SELECT SUM(profit) FROM binance_position_sell')).fetchall(), columns=['profit'])
    profit_sum = df_profit['profit'].iloc[0]
    roi = profit_sum / INITIAL_FUND
    annualized_return = profit_sum / (duration / 24 / 365) / INITIAL_FUND
    annualized_return_percent = f"{annualized_return * 100:.2f}%"

    # Calculate Return as a Percentage
    df['ReturnPercent'] = (df['NetProfit'] / INITIAL_FUND) * 100

    # Plotting the data
    st.markdown(
    f"<div style='text-align: center'>"
    f"Running: {duration_day} | "
    f"ROI: {format_number(roi*100)}% | "
    f"Annualized APY: {annualized_return_percent} | "
    f"Total Profit: {format_number(profit_sum)} USDT"
    f"</div>", unsafe_allow_html=True
    )

    fig, ax1 = plt.subplots(figsize=(10, 6))

    ax1.plot(df['Date'], df['NetProfit'], color='b')
    ax1.set_ylabel('Net Profit', color='b')

    # Create a secondary y-axis for the percentage return
    ax2 = ax1.twinx()
    ax2.plot(df['Date'], df['ReturnPercent'], color='g')
    ax2.set_ylabel('Return (%)', color='g')

    plt.title('Daily Return')
    return fig


def display_annualized_return(engine):

    st.markdown("<h1 style='text-align: center;'>Annualized Return Chart</h1>", unsafe_allow_html=True)
    plt = plot_annualized_return(engine)
    st.pyplot(plt)


def plot_performance_by_coin(engine):
    # Query to calculate the total profit generated by each symbol
    sell_query = "SELECT symbol, SUM(profit) as total_profit FROM binance_position_sell GROUP BY symbol"
    result = engine.connect().execute(text(sell_query)).fetchall()
    df_sell = pd.DataFrame(result, columns=['symbol', 'total_profit'])
    
    # Add a new column 'coin' by slicing the 'symbol' column
    df_sell['coin'] = df_sell['symbol'].str[:-4]

    # Sorting the DataFrame based on total_profit in descending order
    df_sell = df_sell.sort_values(by='total_profit', ascending=False)

    colors = ['red' if x < 0 else 'blue' for x in df_sell['total_profit']]
    
    # Plotting the data
    plt.figure(figsize=(12, 8))
    plt.bar(df_sell['coin'], df_sell['total_profit'], color=colors)
    # plt.xlabel('COINs')
    plt.ylabel('Total Profit')
    plt.title('Performance by coin')
    return plt


def display_performance_by_coin(engine):
    st.markdown("<h1 style='text-align: center;'>Performance by Coin</h1>", unsafe_allow_html=True)
    plt = plot_performance_by_coin(engine)
    st.pyplot(plt)


def display_coin_lists(engine):
    st.markdown("<h1 style='text-align: center;'>Whitelist and Ignore List of Coins</h1>", unsafe_allow_html=True)
    whitelist_query = text("SELECT symbol FROM white_list")
    ignorelist_query = text("SELECT symbol FROM ignore_coin_list")
    df_whitelist = pd.DataFrame(engine.connect().execute(whitelist_query).fetchall(), columns=['symbol'])
    df_ignorelist = pd.DataFrame(engine.connect().execute(ignorelist_query).fetchall(), columns=['symbol'])
    col1, col2 = st.columns(2)
    with col1:
        with st.expander("Whitelist", expanded=False): st.table(df_whitelist)

    with col2:
        with st.expander("Ignore List", expanded=False): st.table(df_ignorelist)

def main():
    display_header()
    display_annualized_return(engine)
    display_performance_by_coin(engine)
    display_coin_lists(engine)
    # Call other display functions here

if __name__ == "__main__":
    main()
