# from Top_functions import *
import streamlit as st
import os, time, base64
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.sql import text
from datetime import datetime
import matplotlib.pyplot as plt
from dotenv import load_dotenv
load_dotenv()

st.set_page_config(
    layout="wide",
    page_icon="🤖",
    )

# Database connection parameters
db_host = os.getenv('DB_HOST')
db_user = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')
db_port = os.getenv('DB_PORT')
db_name = os.getenv('DB_NAME')

engine = create_engine(f'mysql+mysqlconnector://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}',  pool_size=10, max_overflow=20)

INITIAL_FUND = int(os.getenv('INITIAL_FUND', 100_000))


def format_number(num):
    if not num:
        return 0
    if type(num) is dict:
        print(num)
        return 0
    if type(num) is not str and not float and not int:
        return num
    if type(num) is str:
        try:
            num = float(num)
        except Exception as e:
            return num
    positive = 1 if num >= 0 else -1
    num = abs(num)
    if num >= 1000:
        num = int(num)
        num = num * positive
        num = format(num, ',')
        return num
    if num >= 100:
        num = int(num)
        return num * positive
    if num >= 1:
        num = round(num, 2)
        return num * positive
    if num < 0.0001:
        return num * positive
    if num < 1:
        after_0_num = str(num).split('.')[-1]
        list_number = list(after_0_num)
        for i in range(len(list_number)):
            if int(list_number[i]) != 0:
                zero_num = i
                break
        num = round(num, zero_num + 3)
        return num * positive
    

def display_header():
    st.markdown("<h1 style='text-align: center;'>Trading Bot Performance Dashboard</h1>", unsafe_allow_html=True)
    st.markdown("<center>This dashboard provides insights into the Trading Bot's performance.</center>", unsafe_allow_html=True)

def plot_annualized_return(engine):
    query = "SELECT Date, NetProfit FROM net_profit_daily_record"
    df = pd.DataFrame(engine.connect().execute(text(query)).fetchall(), columns=['Date', 'NetProfit'])

    # Calculate Bot Running Time
    df_earliest = pd.DataFrame(engine.connect().execute(text('SELECT MIN(transactTime) FROM binance_position_buy')).fetchall(), columns=['transactTime'])
    earliest_transactTime = df_earliest['transactTime'].iloc[0]
    duration = (int(time.time() * 1000) - earliest_transactTime) / 1000 / 60 / 60
    duration_day = f'{int(duration / 24)} D {int(duration % 24)} H' if duration > 24 else f'{int(duration)} Hours'

    # Calculate Annualized APY
    df_profit = pd.DataFrame(engine.connect().execute(text('SELECT SUM(profit) FROM binance_position_sell')).fetchall(), columns=['profit'])
    profit_sum = df_profit['profit'].iloc[0]
    roi = profit_sum / INITIAL_FUND
    annualized_return = profit_sum / (duration / 24 / 365) / INITIAL_FUND
    annualized_return_percent = f"{annualized_return * 100:.2f}%"

    # Calculate Return as a Percentage
    df['ReturnPercent'] = (df['NetProfit'] / INITIAL_FUND) * 100

    metric_col1, metric_col2, metric_col3 = st.columns(3)
    metric_col1.metric("DUATION", duration_day, datetime.utcfromtimestamp(earliest_transactTime/1000).strftime('%Y-%m-%d'))
    metric_col2.metric("ROI", f"{format_number(roi*100)}%", format_number(profit_sum))
    metric_col3.metric("APY", annualized_return_percent, format_number(annualized_return))
    
    fig, ax1 = plt.subplots(figsize=(12, 8))

    ax1.plot(df['Date'], df['NetProfit'], color='green')
    ax1.set_ylabel('Net Profit', color='black')

    # Create a secondary y-axis for the percentage return
    ax2 = ax1.twinx()
    ax2.plot(df['Date'], df['ReturnPercent'], color='green')
    ax2.set_ylabel('Return (%)', color='black')

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("<h1 style='text-align: center;'>Annualized Return Chart</h1>", unsafe_allow_html=True)
        plt.title('Daily Return')
        st.pyplot(fig)

    with col2:
        st.markdown("<h1 style='text-align: center;'>Performance by Coin</h1>", unsafe_allow_html=True)
        plt.title('Performance by coin')
        plot_performance_by_coin(engine)

    return

def plot_performance_by_coin(engine):
    # Query to calculate the total profit generated by each symbol
    sell_query = "SELECT symbol, SUM(profit) as total_profit FROM binance_position_sell GROUP BY symbol"
    sell_count_query = "SELECT symbol, COUNT(*) as trade_count FROM binance_position_sell GROUP BY symbol"
    
    result = engine.connect().execute(text(sell_query)).fetchall()
    df_sell = pd.DataFrame(result, columns=['symbol', 'total_profit'])
    
    count_result = engine.connect().execute(text(sell_count_query)).fetchall()
    df_count = pd.DataFrame(count_result, columns=['symbol', 'trade_count'])

    # Merge the two dataframes on symbol
    df_merged = pd.merge(df_sell, df_count, on='symbol')
    
    # Add a new column 'coin' by slicing the 'symbol' column
    df_merged['coin'] = df_merged['symbol'].str[:-4]

    # Filter to top 10 positive and top 5 negative profit coins
    top_positive = df_merged[df_merged['total_profit'] > 0].nlargest(5, 'total_profit')
    top_negative = df_merged[df_merged['total_profit'] < 0].nsmallest(5, 'total_profit')
    df_filtered = pd.concat([top_positive, top_negative]).sort_values(by='total_profit', ascending=False)

    colors = ['red' if x < 0 else 'green' for x in df_filtered['total_profit']]
    
    # Plotting the total profit
    fig, ax1 = plt.subplots(figsize=(12, 8))
    ax1.bar(df_filtered['coin'], df_filtered['total_profit'], color=colors)
    ax1.set_ylabel('Total Profit', color='black')
    ax1.tick_params(axis='y', labelcolor='black')

    # Create a secondary y-axis for trade count
    ax2 = ax1.twinx()
    ax2.plot(df_filtered['coin'], df_filtered['trade_count'], color='grey', marker='o', linestyle='-')
    ax2.set_ylabel('Trade Count', color='black')
    ax2.tick_params(axis='y', labelcolor='black')

    # Add labels and title
    plt.xticks(rotation=45)
    # ax1.set_xlabel('Coins')
    plt.title('Top Performing and Worst Performing Coins')

    st.pyplot(fig)
    return 


def display_coin_lists(engine):
    st.markdown("<h1 style='text-align: center;'>Whitelist and Ignore List of Coins</h1>", unsafe_allow_html=True)
    whitelist_query = text("SELECT symbol FROM white_list")
    ignorelist_query = text("SELECT symbol FROM ignore_coin_list")
    df_whitelist = pd.DataFrame(engine.connect().execute(whitelist_query).fetchall(), columns=['symbol'])
    df_ignorelist = pd.DataFrame(engine.connect().execute(ignorelist_query).fetchall(), columns=['symbol'])
    col1, col2 = st.columns(2)
    with col1:
        with st.expander("Whitelist", expanded=False): st.table(df_whitelist)

    with col2:
        with st.expander("Ignore List", expanded=False): st.table(df_ignorelist)


def display_binance_position_sell(engine):
    df_sell = pd.DataFrame(engine.connect().execute(text('SELECT symbol, type, profit, clientOrderId, transactTime, price, update_id FROM binance_position_sell WHERE clientOrderId != "AAAAAAAAAAAAAAAAAAAAAA" AND price != 0 ORDER BY update_id DESC')).fetchall())
    df_buy = pd.DataFrame(engine.connect().execute(text('SELECT symbol, type, clientOrderId, transactTime, price, update_id FROM binance_position_buy WHERE is_closed = 1 ORDER BY update_id DESC')).fetchall())
    df_merged = pd.merge(df_buy, df_sell, on='update_id', suffixes=('_buy', '_sell'))
    df_merged['coin'] = df_merged['symbol_buy'].str[:-4]
    df_merged['duration'] = df_merged['transactTime_sell'] - df_merged['transactTime_buy']
    df_merged['duration_min'] = df_merged['duration'].apply(lambda x: int(x/1000/60))
    df_merged['transactTime_buy'] = df_merged['transactTime_buy'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
    df_merged['transactTime_sell'] = df_merged['transactTime_sell'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
    df_merged.drop(['symbol_buy', 'symbol_sell', 'duration'], axis=1, inplace=True)
    df_merged = df_merged[['update_id', 'coin', 'profit', 'type_buy', 'type_sell', 'duration_min', 'transactTime_buy', 'transactTime_sell', 'price_buy', 'price_sell', 'clientOrderId_buy', 'clientOrderId_sell']]

    # offer a download link for the dataframe as a csv file
    csv = df_merged.to_csv(index=False)
    b64 = base64.b64encode(csv.encode()).decode()
    href = f'<a href="data:file/csv;base64,{b64}" download="binance_position_buy_sell.csv">Download CSV File</a>'
    st.markdown(href, unsafe_allow_html=True)

    with st.expander("Position BUY & SELL History", expanded=False):  st.table(df_merged)

    return


def display_open_position(engine):
    df_buy = pd.DataFrame(engine.connect().execute(text('SELECT coin, type, orderId, transactTime, price, update_id FROM binance_position_buy WHERE is_closed = 0 ORDER BY update_id DESC')).fetchall())
    # Add duration column
    df_buy['duration'] = int(time.time() * 1000) - df_buy['transactTime']
    df_buy['duration_hour'] = df_buy['duration'].apply(lambda x: int(x/1000/60/60))
    # Make transactTime string format
    df_buy['transactTime'] = df_buy['transactTime'].apply(lambda x: datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M'))
    # drop 'duration' column
    df_buy.drop(['duration'], axis=1, inplace=True)
    with st.expander("Open Positions", expanded=False): 
        if df_buy.empty:
            st.write("No open positions currently.")
        else: st.table(df_buy)
    return 


def display_funding_account_positions(engine):
    try: df = pd.DataFrame(engine.connect().execute(text(f'SELECT * FROM binance_funding_positions WHERE is_closed = 0')).fetchall())
    except: pd.DataFrame()
    with st.expander("Funding Account Positions", expanded=False): 
        if df.empty: 
            st.write("No funding account positions currently.")
        else:
            st.table(df)


def display_funding_account_performance(engine):
    try: df = pd.DataFrame(engine.connect().execute(text(f'SELECT * FROM binance_funding_profits')).fetchall())
    except: pd.DataFrame()

    with st.expander("Funding Account Performance", expanded=False): 
        if df.empty: st.write("No funding account performance data.")
        else:
            total_profit = df['profit'].sum()
            st.write(f"Total Profit: {format_number(total_profit)}")
            st.table(df)


def daily_profit_take_record(engine):
    try: df_today = pd.DataFrame(engine.connect().execute(text('SELECT * FROM daily_profit_take')).fetchall()) 
    except: df_today = pd.DataFrame()

    with st.expander("Daily Profit Take Record", expanded=False): 
        if df_today.empty: st.write("No daily profit take record.")
        else: st.table(df_today)


def main():
    display_header()
    
    plot_annualized_return(engine)

    display_open_position(engine)

    display_binance_position_sell(engine)

    display_funding_account_positions(engine)

    display_funding_account_performance(engine)

    display_coin_lists(engine)

    daily_profit_take_record(engine)
    # Call other display functions here

if __name__ == "__main__":
    main()
